DECLARE @TABLE SYSNAME;

SET @TABLE = 'TOTO';

SELECT 'SELECT ''' + NAME + ''' COLNAME,'+
'MIN(LEN('+ Name +')) MIN_LEN,'+
'MAX(LEN('+ NAME +')) MAX_LEN,'+
'AVG(LEN('+ NAME +')) AVG_LEN' +
' FROM '+@TABLE+' WITH(NOLOCK) UNION ALL ' colsql
FROM SYS.COLUMNS C WHERE
OBJECT_ID=OBJECT_ID(@TABLE);